### ISSUE TITLE
Get list of devices

### ISSUE THREAD

**Issue by nakata5321** [Multi-Agent-io/robonomics-interface#30]
Implement the method, which will return list of devices for a given address. Similar to `chainstate` option. Check it here: **Develop -> chainstate -> rws -> devices.**

**Comment by PaTara43** [comment]
It's actually 0.5.5 though:D

https://github.com/Multi-Agent-io/robonomics-interface/commit/114cd0ace26f293fa489381306acaed1e7bbd0ed
