### ISSUE TITLE
Subscriber for multiple addresses

### ISSUE THREAD

**Issue by nakata5321** [Multi-Agent-io/robonomics-interface#31]
Give the ability to subscribe for several addresses, not for only one.
See it here: https://github.com/Multi-Agent-io/robonomics-interface/blob/main/robonomicsinterface/RobonomicsInterface.py#L501

**Comment by PaTara43** [comment]
https://github.com/Multi-Agent-io/robonomics-interface/commit/a01430a071c0d241bf9a3452ee33402769c55281
