### ISSUE TITLE
Add watchers functionality to the library 

### ISSUE THREAD

**Issue by Vourhey** [Multi-Agent-io/robonomics-interface#4]
It would be good to have some kind of a watcher function with a callback for an event. For example, I could wish to subscribe for a new datalog record event with something like this:

```
def new_datalog_record_handler(record):
    print(record)

ri.subscribe_to_datalog(handler = new_datalog_record_handler)
```

**Comment by PaTara43** [comment]
1a4e88e3f37305f97431b1667af1659af573e997
278ff6a4f59ea1de3867ffe442e26dc70fb05b10
db4073a89d76c851c804ddc18d05bc26101515d9
5a9e244266ebff8373e6bbfb3e11102bafd733da
e8b985ad5782be3b97ca30baf7733b057c223784
81b8e3817412f99d80200b5d2f08f72f787c6d01
