### ISSUE TITLE
Add cli commands 

### ISSUE THREAD

**Issue by Vourhey** [Multi-Agent-io/robonomics-interface#5]
In [robonomics](https://github.com/airalab/robonomics) binary we have `robonomics io` module. But it's not persistent in releases. However it would be good to have access to the library functionality without writing an actual code but rather using an executable script

Please consider adding `riio` (or call whatever you like) to the repository with at least `write datalog`, `read datalog`, `write launch`, `read launch` functions

**Comment by PaTara43** [comment]
cbf1de51883076ec97bb7a3a36e62ef7017956e0
4cb18e4378fb445cb2f34a31c4895b523b0076b1
1ac66509949830de0f3213f44d55775b17a05c98
2217547c4ed847421d3497b3dc332249ae42fc06
cd9b9c91bda70461ab19319453761a4120469003
