### ISSUE TITLE
How can I get transaction identity to `Subscriber` callback?

### ISSUE THREAD

**Issue by khssnv** [Multi-Agent-io/robonomics-interface#64]
Hi there :wave:
How can I get transaction identity to `Subscriber` callback?

A callback caller does not pass it and there is no identity in event attributes.
https://github.com/Multi-Agent-io/robonomics-interface/blob/bea0e5a9900bbb7788d0a26a70e46aa9e2f3c6c5/robonomicsinterface/classes/subscriptions.py#L85

I made a PR https://github.com/Multi-Agent-io/robonomics-interface/pull/63 to add this functionality, please let me know if there is any better way.

**Comment by PaTara43** [comment]
Hi!
Please, consider the pr review

**Comment by PaTara43** [comment]
https://github.com/Multi-Agent-io/robonomics-interface/pull/65
