### ISSUE TITLE
Get current nonce function

### ISSUE THREAD

**Issue by nakata5321** [Multi-Agent-io/robonomics-interface#7]
Add get_account_nonce function like in substrate interface
https://github.com/polkascan/py-substrate-interface/blob/154ff1ce2e2648d96818200c86ba5889fc5c60d2/substrateinterface/base.py#L1432

**Comment by nakata5321** [comment]
Also I need the ability to set **nonce** when I create a *custom extrinsic*. You realize this function here:

https://github.com/Multi-Agent-io/robonomics-interface/blob/8ec45d055fc2e8ec4ba176bac4e13a7223758f0d/robonomicsinterface/RobonomicsInterface.py#L144

On substrate interface you cal set **nonce** in *create_signed_extrinsic* function.

https://github.com/polkascan/py-substrate-interface/blob/master/substrateinterface/base.py#L1513

**Comment by PaTara43** [comment]
https://github.com/Multi-Agent-io/robonomics-interface/commit/e09d75af89c09be043d6605de6ead9c0271e941a
